import { NextApiRequest, NextApiResponse } from "next";
import PDFDocument from "pdfkit";

export default async function handler(req: NextApiRequest, res: NextApiResponse<any>) {
    
    try {
        if (req.method === 'POST') {
            // Create a new PDF document
            const doc = new PDFDocument();
            
            // Set response headers for PDF
            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', 'attachment; filename="document.pdf"');
            
            // Pipe the PDF into the response
            doc.pipe(res);
            
            // Add content to the PDF
            doc.fontSize(20).text('Generated PDF Document', 100, 100);
            doc.fontSize(12).text('This PDF was generated by the getPDF API endpoint.', 100, 150);
            doc.text('Date: ' + new Date().toLocaleDateString(), 100, 180);
            
            // You can add more content based on request data
            if (req.body && req.body.content) {
                doc.text('Custom Content:', 100, 220);
                doc.text(req.body.content, 100, 250);
            }
            
            // Finalize the PDF
            doc.end();
            
        } else {
            res.status(405).json({ error: 'Method Not Allowed' });
        }
    } catch (err) {
        console.log(err, process.env); 
        res.status(500).json({ error: 'Failed to generate PDF' });
    }
}