import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.scss";
import Link from "next/link";
import Image from 'next/image';

import faceBookIcon from "../svg/facebook.svg";
import instagramIcon from "../svg/instagram.svg";
import linkedinIcon from "../svg/linkedin.svg";
import twitterIcon from "../svg/x.svg";
import HeaderNavigation from "@/components/headerNavigation";


const heebo = localFont({
  src: [
    {
      path: '../public/fonts/heebo/Heebo-Thin.ttf',
      weight: '100'
    },
    {
      path: '../public/fonts/heebo/Heebo-ExtraLight.ttf',
      weight: '200'
    },
    {
      path: '../public/fonts/heebo/Heebo-Light.ttf',
      weight: '300'
    },
    {
      path: '../public/fonts/heebo/Heebo-Regular.ttf',
      weight: '400'
    },
    {
      path: '../public/fonts/heebo/Heebo-Medium.ttf',
      weight: '500'
    },
    {
      path: '../public/fonts/heebo/Heebo-SemiBold.ttf',
      weight: '600'
    },
    {
      path: '../public/fonts/heebo/Heebo-Bold.ttf',
      weight: '700'
    },
    {
      path: '../public/fonts/heebo/Heebo-ExtraBold.ttf',
      weight: '800'
    },
    {
      path: '../public/fonts/heebo/Heebo-Black.ttf',
      weight: '900'
    }
  ],
  variable: '--font-heebo'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${heebo.variable} font-sans`}>
      <body className="text-dark">
        <header>
          <HeaderNavigation></HeaderNavigation>
        </header>
        <main>{children}</main>
        <div className="h-[11.375rem] mt-[4rem] flex flex-col items-center">
            <div className="flex w-[14.375rem] justify-between">
              <Link href="https://www.facebook.com/kobi.krasnoff" target="_blank">
                <Image
                  priority
                  src={faceBookIcon}
                  alt="Follow me on facebook"
                />
              </Link>
              <Link href="https://www.instagram.com/kobikrasnoff/" target="_blank">
                <Image
                  priority
                  src={instagramIcon}
                  alt="Follow me on Instagram"
                />
              </Link>
              <Link href="https://www.linkedin.com/in/kobi-krasnoff-7510689/" target="_blank">
                <Image
                  priority
                  src={linkedinIcon}
                  alt="Follow me on Linkedin"
                />
              </Link>
              <Link href="https://twitter.com/krasnoffkobi" target="_blank">
                <Image
                  priority
                  src={twitterIcon}
                  alt="Follow me on twitter"
                  className="w-[27px] h-[27px]"
                />
              </Link>
            </div>
            <div className="flex content-center mt-[1.875rem] text-[0.875rem]">
              Copyright ©2024 All rights reserved 
            </div>
        </div>
      </body>
    </html>
  );
}
